### ISSUE TITLE
Make up-arrow visible on privacy-policy page and smooth scroll

### ISSUE THREAD

**Issue by gautamjajoo** [Cloud-CV/EvalAI-ngx#106]
### Observered Behaviour
The up-arrow is not visible on privacy-page when scrolled at the bottom of the page.

### Expected Behaviour 
The up-arrow should be visible and a smooth scroll effect to it.

@RishabhJain2018

**Comment by sanketbansal** [comment]
can i work on this issue? i have already made some changes in privacy policy page.

**Comment by sanketbansal** [comment]
Have opened a pull request which fixes the issue of arrow-visibility at the bottom of the page.
https://github.com/Cloud-CV/EvalAI-ngx/pull/111#issue-261875265.
