### ISSUE TITLE
Remove the scroll bar after “Who uses EvalAI”

### ISSUE THREAD

**Issue by gautamjajoo** [Cloud-CV/EvalAI-ngx#108]
### Observed Behaviour 
Scroll bar is visible under `Who uses EvalAI` on normal screen. The scroll bar is used for medium and small screen. Find attached screenshot.

### Expected Behaviour
The scroll bar should not be visible on normal screen.

@RishabhJain2018 

![a](https://user-images.githubusercontent.com/24366008/54494425-2c165700-4900-11e9-87ca-0136b5899951.png)

**Comment by Abhi58** [comment]
@RishabhJain2018 @gautamjajoo  In PR #108 I have removed the scroll bar and also build is successfull  but surge is not able to login. Please look into this issue.

**Comment by RishabhJain2018** [comment]
Hi @Abhi58 , Thanks for the PR. I'll surely fix the surge issue by tonight and we can start merging your PR's.

**Comment by Abhi58** [comment]
@RishabhJain2018 Thanks.
