### ISSUE TITLE
Modifying Dashboard UI

### ISSUE THREAD

**Issue by sivapalivela** [Cloud-CV/EvalAI-ngx#119]
## I'm submitting a

(Check one with "x" from given options)
- [ ] Bug report
- [x ] Feature request

## Current behavior
![Screenshot from 2019-04-03 23-37-24](https://user-images.githubusercontent.com/24860714/55502120-7706cd00-5669-11e9-8801-adb96297ca28.png)

## Expected behavior

![Screenshot from 2019-04-03 23-34-25](https://user-images.githubusercontent.com/24860714/55502134-8128cb80-5669-11e9-97ca-03038e389c2d.png)

## Other information
Making using of Angular Material and Font Awesome Icons would make it more attractive 
(Angular FlexLayout could solve some issues related to responsiveness)

**Comment by sivapalivela** [comment]
Sir, Can I start working on this issue ?

**Comment by Shekharrajak** [comment]
Sure!
