### ISSUE TITLE
Add a check for the project and publication url fields under submit tab

### ISSUE THREAD

**Issue by Sanji515** [Cloud-CV/EvalAI-ngx#169]
## Current behavior

Currently, there is no check for the project and publication url fields when making submissions under the `Submit` tab

## Expected behavior

There should be a check for the above mentioned fields if they are real.

**Comment by Abhi58** [comment]
I am working on this issue. Please assign it to me @Sanji515 . Thanks!

**Comment by Sanji515** [comment]
Hey @Abhi58 it is already been fixed [here](https://github.com/Cloud-CV/EvalAI-ngx/pull/231). Please feel free to take some other issue. Closing this.

**Comment by Abhi58** [comment]
Okay. Thanks for the update! @Sanji515
