### ISSUE TITLE
Implement the authservice

### ISSUE THREAD

**Issue by xamfy** [Cloud-CV/EvalAI-ngx#17]
Implement the isLoggedin function
- check the presence of token in localstorage

**Comment by aka-jain** [comment]
@xamfy authService has already been implemented. Regarding token we will open an issue when we done with the auth functionality. Let me know if you have any concern. Otherwise we will reopen this issue after completing auth functionality.

**Comment by xamfy** [comment]
got it, how will you take forward the auth functionality? Can I help with that.

**Comment by aka-jain** [comment]
@xamfy We are working on designing of product that's why it's getting little late. Will open plenty of issue soon. Till then read about the best practices for Angular 5 and we really want some good suggestions from everyone.

Till then I'm closing this issue.
