### ISSUE TITLE
Spacing issue in login page

### ISSUE THREAD

**Issue by sachinmukherjee** [Cloud-CV/EvalAI-ngx#207]
# Bug Report
There Should a Space between **Already have an account?** and **Log In**
## Current Behaviour
<i>Already have an account?Log In</i>
## Expected Behaviour
<i>Already have an account? Log In</i>

@RishabhJain2018  I want to solve this issue.

**Comment by galipremsagar** [comment]
@sachinmukherjee feel free to raise a PR with the fix.
