### ISSUE TITLE
Fix Typo

### ISSUE THREAD

**Issue by Arun-Jain** [Cloud-CV/EvalAI-ngx#22]
Close bracket is missing in performance comparison.
![screenshot_2018-02-28-00-43-52](https://user-images.githubusercontent.com/16155501/36749750-b1c7d1b0-1c21-11e8-977c-39548f534dfc.png)

**Comment by spyshiv** [comment]
@Arun-Jain assigning this to you. Please fix that ASAP.

**Comment by aka-jain** [comment]
Fixed with #26 . Closing this.
