### ISSUE TITLE
Create header component for EvalAI home page

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI-ngx#23]
Attaching design for EvalAI home page intro section. 
![evalai_redesign_2](https://user-images.githubusercontent.com/11537940/36750880-a531f69e-1c24-11e8-82f9-9e6f997c0a36.jpg)

Create header according to the attached design.
Follow `variables.scss` for styling (add new variables wherever needed).

Note: Try to make responsive header.

Let us know in case of any query.

**Comment by muddlebee** [comment]
@aka-jain  Can I try this?

**Comment by aka-jain** [comment]
Yes @anweshknayak , please go ahead.

**Comment by spyshiv** [comment]
@anweshknayak sure! Go ahead. Assigning this to you.

**Comment by muddlebee** [comment]
@spyshiv @aka-jain Do I need to create a separate `components` folder in `EvalAI-ngx/src/app/` for the header component ?

**Comment by aka-jain** [comment]
Yes @anweshnayak.

**Comment by muddlebee** [comment]
@aka-jain  I think I should wait for #24 ? Or I just create separate button styles for header component?

**Comment by aka-jain** [comment]
Just place dummy buttons for now. Will open a separate issue for that.
