### ISSUE TITLE
Create common button styles for EvalAI

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI-ngx#24]
Attaching design of EvalAI home page for the reference.

Create buttons as used in this design (white and transparent). basically, you have to add common styles for these buttons (modular scss).

Let us know in case of any query.

![evalai_redesign_2](https://user-images.githubusercontent.com/11537940/36751072-1e4e52c0-1c25-11e8-9887-5d4a6d051c05.jpg)

**Comment by ParthS007** [comment]
@aka-jain  I want to work on this , can you please tell where I have to do the changes . Thanks  :smiley:

**Comment by harshit98** [comment]
Working on it @aka-jain.

**Comment by aka-jain** [comment]
@ParthS007 please pick up one issue at a time.

@harshit98 assigning this to you.

**Comment by RishabhJain2018** [comment]
@live-wire I feel this is done? If yes, please feel free to close the issue.

**Comment by live-wire** [comment]
It is done as a part of the PR for #23
