### ISSUE TITLE
Add font family.

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI-ngx#25]
Add `Open Sans` font family for global styling.
Steps for creation:

- Create a new file `fonts.scss` for this addition
- Import it in base.scss.

Here is the reference link https://fonts.google.com/specimen/Open+Sans
Please let us know in case of any query.

**Comment by ParthS007** [comment]
@aka-jain I want to work on this . Can I proceed with it ?

**Comment by aka-jain** [comment]
Sure @ParthS007, assigning this to you.

**Comment by harshit98** [comment]
Working on it. @ParthS007 you're already working on #24 😄 

Can we divide some work among ourselves?

**Comment by ParthS007** [comment]
@harshit98  you can start working on #24 . I am going with this issue :+1:

**Comment by aka-jain** [comment]
@harshit98 please pick up another issue. This has been already assigned to @ParthS007

**Comment by aka-jain** [comment]
@ParthS007 any update on this?

**Comment by Obtin** [comment]
@aka-jain, is anybody working on this if not I would like to take this up
