### ISSUE TITLE
Unable to run EvalAI-ngx locally 

### ISSUE THREAD

**Issue by sraghuvanshi** [Cloud-CV/EvalAI-ngx#291]
Sir, I tried to run the EvalAI-ngx code on my local machine using the command given in readme.

> docker-compose up

However, it shows the following error: 

> evalai_ngx   | Schema validation failed with the following errors:
> evalai_ngx   |   Data path ".builders['app-shell']" should have required property 'class'.

I'm running it on ubuntu 18.04. I've attached the screenshots of the terminal and localhost:8000 for reference. 

Please look into it. Thank you.

## Screenshots
![Screenshot from 2020-02-17 06-44-08](https://user-images.githubusercontent.com/48951339/74620645-db3a5e80-515f-11ea-8e34-fba22bdde201.png)
![Screenshot from 2020-02-17 06-43-49](https://user-images.githubusercontent.com/48951339/74620653-e1c8d600-515f-11ea-8913-b8e26406d2dd.png)
![Screenshot from 2020-02-17 06-43-56](https://user-images.githubusercontent.com/48951339/74620656-e4c3c680-515f-11ea-8017-8e51df5f7310.png)
![Screenshot from 2020-02-17 06-45-55](https://user-images.githubusercontent.com/48951339/74620661-e8574d80-515f-11ea-8fcc-0b6059191cfb.png)

**Comment by Kajol-Kumari** [comment]
@sraghuvanshi I think there is already an issue opened for this #249 .So, please close this issue and for temporary solution regarding setting up the development environment please go through the comments of #249

**Comment by sraghuvanshi** [comment]
Sure @Kajol-Kumari, Thank you for referring to the issue #249.
