### ISSUE TITLE
Update Issue and PR template 

### ISSUE THREAD

**Issue by ParthS007** [Cloud-CV/EvalAI-ngx#31]
**Expected behavior**

Presently, Contributor has to do a lot of changes in Issue and PR  template. One has to remove lots of text present already in templates and then has to edit according to issue/PR.

**Observed behavior**
There should be simple templates so that contributor has to just mention the bug/feature instead of editing and removing lots of text.

**Comment by deshraj** [comment]
Thanks @ParthS007. I really liked this idea. :)

**Comment by ParthS007** [comment]
@deshraj  Can you please review #32 , I have updated the templates. Please give suggestions if there are any changes required. Thanks

**Comment by deshraj** [comment]
Done.
