### ISSUE TITLE
Git clone statement error

### ISSUE THREAD

**Issue by S2606** [Cloud-CV/EvalAI-ngx#35]
## I'm submitting a

(Check one with "x" from given options)
- [X] Bug report
- [ ] Feature request

## Current behavior
On using ``git clone git@github.com:Cloud-CV/EvalAI-ngx.git`` it gives an error regarding access rights

## Expected behavior
Change the statement to ``git clone https://github.com/Cloud-CV/EvalAI-ngx``

I would like to work on this

**Comment by S2606** [comment]
@deshraj Please review

**Comment by aka-jain** [comment]
@S2606 do you want to update the README or something else?

**Comment by S2606** [comment]
Yes @aka-jain

**Comment by aka-jain** [comment]
Cool, please go ahead. @S2606

**Comment by spyshiv** [comment]
@S2606 you don't need to change url. You should mention that 
if a someone haven't integrated ssh key to GitHub account then use `git clone https://github.com/Cloud-CV/EvalAI-ngx` otherwise it's totally fine

**Comment by S2606** [comment]
@aka-jain Should I make the requested change??

**Comment by spyshiv** [comment]
@S2606 yes.
