### ISSUE TITLE
Auto deployment of every PR using Surge

### ISSUE THREAD

**Issue by ParthS007** [Cloud-CV/EvalAI-ngx#40]
## I'm submitting a

(Check one with "x" from given options)
- [ ] Bug report
- [x] Feature request

## Current behavior
At present, there is no auto deployment of Pull request.

## Expected behavior
There should be auto deployment of PR which will ease the review process.

Mentors, Please give your views on this.

I want to work on this.

**Comment by ParthS007** [comment]
@deshraj @aka-jain @RishabhJain2018 @spyshiv  Please give your views on this feature.

**Comment by ParthS007** [comment]
@spyshiv  Can I start working on this?

**Comment by spyshiv** [comment]
@ParthS007 Sounds interesting. Go ahead
