### ISSUE TITLE
Add Codecov support for code coverage

### ISSUE THREAD

**Issue by ParthS007** [Cloud-CV/EvalAI-ngx#41]
## I'm submitting a

(Check one with "x" from given options)
- [ ] Bug report
- [x] Feature request

## Current behavior
At present, there is no support for testing code coverage.

## Expected behavior
There should be a support for testing code coverage as code coverage is a measurement used to express the degree to which the source code is executed when a test suite runs. 

@deshraj @aka-jain @RishabhJain2018 @spyshiv  Please give suggestions.

I want to work on this issue.

**Comment by spyshiv** [comment]
thanks @ParthS007 for opening this issue. Go ahead. 
I hope to see a PR for this very soon.
