### ISSUE TITLE
Ahead-of-Time Compilation for production builds

### ISSUE THREAD

**Issue by muddlebee** [Cloud-CV/EvalAI-ngx#42]
More here : https://help.syncfusion.com/angular/gettingstarted/getting-started-with-webpack-aot

Why do Ahead-of-Time Compilation

-    Faster Rendering
-    Fewer asynchronous requests
-    Smaller Angular framework download size
-    Detect template errors earlier
-    Better security

@aka-jain @spyshiv

**Comment by aka-jain** [comment]
Thanks for pointing this out @anweshnayak. We will use AOT at the time of bundling. Bit it's not useful for development purpose. So, closing this issue for now.
