### ISSUE TITLE
Create UI for EvalAI Pages

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI-ngx#46]
## How does the new UI look?

EvalAI team has been working on the new UI for last one month. We have come up with this mock-up of the home page (yes it takes a lot of time in planning and discussion. Special thanks to @shivaniprakash95 for taking lead on this):

![evalai_redesign_homepage_2](https://user-images.githubusercontent.com/2945708/37508608-31e6984a-28ca-11e8-90aa-393ff105fa10.jpg)

Note that the second last section is still empty and we want to show twitter feed there in that section.

## Deliverables

Now that we have shared the mockup design, we expect the student to have the following things ready by 27th March 2018 (GSoC Proposal submission deadline):

1. Create an HTML page with the exact same design (it's quite easy, right?). We also expect modular code structure for this particular task since the code will get merged to the master branch at the end of the day if you do a really good job at this. **(Additional points if you can make the pages responsive)**
2. **Extended Goal**: We also expect the students to think more and create UI with similar design pattern for other pages such as Challenge list page, challenge details, submission, leaderboard, login/signup etc.
3. Create a video for the same showing how the page looks. 
4. Share the link to the code in 

## How to get started?

All the important information has been shared on this issue. We look forward to seeing some really cool pages before the GSoC proposal submission deadline. Please let us know if you have questions. Mentors for EvalAI-ngx Project (@aka-jain @spyshiv @shivaniprakash95 @RishabhJain2018 @deshraj) will try to respond to this thread ASAP so that you are not blocked.

**Comment by muddlebee** [comment]
@deshraj  could you provide the assets (background images like the blue one, fonts, buttons) used? If not at all atleast the background images. 

It will be hard doing the whole thing using css from scratch. Given we have limited time for proposal submission.

**Comment by ParthS007** [comment]
I would also like to work on this @deshraj .
We can collaborate @anweshknayak  if you are working on it . 
What's your view on this ?

**Comment by aka-jain** [comment]
@ParthS007 you have to do this task individually.

**Comment by shivaniprakash19** [comment]
Hi Anwesh, we will surely provide you with the documentation as well as
with the assets as soon as possible.

**Comment by shivaniprakash19** [comment]
@anweshknayak This is the link to the assets and image for reference.[https://drive.google.com/drive/folders/1BZYFcsegI_1dHhv44Ef208Kzt-XMvBNJ?usp=sharing
![evalai_redesign_documentation](https://user-images.githubusercontent.com/12206049/37562780-866c21aa-2a96-11e8-952e-40f5e8785b7c.jpg)
](url)

**Comment by geekyharshal** [comment]
Link not working> :/ 
![screenshot 310](https://user-images.githubusercontent.com/15772947/37563588-2e87a5ae-2aaa-11e8-872c-7c3d6213da0e.png)

**Comment by shivaniprakash95** [comment]
@geekyharshal  There was some issue with the previous link. This is the updated one. [https://drive.google.com/open?id=1BZYFcsegI_1dHhv44Ef208Kzt-XMvBNJ](url)

**Comment by shivaniprakash19** [comment]
There was some issue with the previous link. This is the updated one : https://drive.google.com/drive/folders/1p2_oOLrgLwh7wHtSOowUtORgAf-ira3m?usp=sharing

**Comment by muddlebee** [comment]
hey @shivaniprakash95 :wave: 

These two image cards are missing. 
![evalai_redesign_documentation](https://user-images.githubusercontent.com/8139783/37603853-90c5d1bc-2bb5-11e8-86dd-5cf2c31cc94e.jpg)

or it is something we have to come up on our own?

Looks like the upper image is the old EvalAI design and the one below is something can be done in CSS.

**Comment by gautamjajoo** [comment]
@anweshknayak 
All the images are in the "Header Section" !!

**Comment by muddlebee** [comment]
@gautamjajoo thanks. I missed it

**Comment by muddlebee** [comment]
@shivaniprakash95 please provide icon packs too. (Location, Quotation and others used in testimonial card)

**Comment by shivaniprakash19** [comment]
@anweshknayak There is a background image in the link provided earlier(google drive link). You can use any similar quotation of a font, and you can get a similar location icon too, please search for it on the website named, flaticon. Let me know if there is still a problem : )

**Comment by pavanrkadave** [comment]
Hi i would like to work on this issue.

**Comment by RishabhJain2018** [comment]
Hi @pavanrkadave We already have a new home page ready and we would like to enhance it. Please try running this new frontend and feel free to ask doubts/questions. I'll be happy to help.

**Comment by RishabhJain2018** [comment]
Closing this since we already have the UI.
