### ISSUE TITLE
Create UI for privacy page

### ISSUE THREAD

**Issue by spyshiv** [Cloud-CV/EvalAI-ngx#50]
## UI Design for privacy page

Here is the final design. Please refer to screenshot below.
 
![evalai_redesign_privacy_final_updated](https://user-images.githubusercontent.com/12206049/39088686-12d47518-45d4-11e8-8e6e-b49f75ddc4e4.jpg)

---

Please comment below if you want to work on this or in case of any question/suggestion.

@shivaniprakash95  please share the details about `assets` and `content` that will be needed for this.

**Comment by shivaniprakash19** [comment]
You can get the relevant text from the present website itself : https://evalai.cloudcv.org/privacy-policy

You can either get to the the documentation and assets of the page by visiting this link : https://drive.google.com/drive/folders/1ex7pKE7UkiX9tJedGPPgBFi5VBzLfVuO?usp=sharing
or you can download it as an attachment : 
Documentation ( There is a slight change, as compared to that of earlier one)
![evalai_redesign_privacy_final_documentation_updated](https://user-images.githubusercontent.com/12206049/39088688-3146e026-45d4-11e8-980b-433f000d8d81.jpg)

EvalAI logo
![evalai_logo](https://user-images.githubusercontent.com/12206049/38831006-b68804a6-41db-11e8-8500-6c1713553c7e.png)
