### ISSUE TITLE
UI Design for Login page

### ISSUE THREAD

**Issue by shivaniprakash19** [Cloud-CV/EvalAI-ngx#51]
**Here is the final design. Please refer to screenshot below.**

![evalai_redesign_loginpage_final](https://user-images.githubusercontent.com/12206049/38850904-1ac74ada-4231-11e8-9e1a-c2d1df062e1b.jpg)

You can refer to the following image for further details on creating the page : 
![evalai_redesign_loginpage_final_documentation](https://user-images.githubusercontent.com/12206049/38851026-9902843c-4231-11e8-8aa8-7434facc737f.jpg)

You can get all the related assets for creating the page from the link below : 
https://drive.google.com/drive/folders/1JsK6l1B5pSKJY2MCSMQVZYq1EwGuOx4t

Please comment below if you want to work on this or in case of any question/suggestion.

Mentors for EvalAI-ngx Project (**@aka-jain @spyshiv @shivaniprakash95 @RishabhJain2018 @deshraj**) will try to respond to this thread ASAP so that you are not blocked.

**Comment by shivaniprakash19** [comment]
These are the additional icons for SignUp page. Please take reference from the present website so as to get the exact picture of things. Here is the link to the page: https://evalai.cloudcv.org/auth/signup

You can also find the same images on the drive link : https://drive.google.com/drive/folders/1TybetGkutjjndRdoRdx41KHR7-x6WCA4
![confirm_icon](https://user-images.githubusercontent.com/12206049/39631720-9a0fbdca-4fd0-11e8-9ddc-813e068a5f66.png)
![close-envelope](https://user-images.githubusercontent.com/12206049/39631722-9a5b8dd6-4fd0-11e8-8eec-620a01c2e094.png)

**Comment by RishabhJain2018** [comment]
Closing this since it is already merged.
