### ISSUE TITLE
UI Design for About Us page 

### ISSUE THREAD

**Issue by shivaniprakash19** [Cloud-CV/EvalAI-ngx#52]
**Here is the final design. Please refer to screenshot below.**

![about_us_final](https://user-images.githubusercontent.com/12206049/39149576-29b0fb0a-475d-11e8-96a8-d83d6de3bc6e.jpg)

**You can refer to the following image for further details on creating the page :**

![about_us_final_documentation](https://user-images.githubusercontent.com/12206049/39149604-4df121de-475d-11e8-9956-d11dfdca7a5a.jpg)

You can get all the related assets for creating the page from the link below :
https://drive.google.com/drive/folders/1VIEmGtKwBEOs_kzFu6lGFfnCzXm9GyB9

You can get the relevant text from the present website itself : https://evalai.cloudcv.org/about

Please comment below if you want to work on this or in case of any question/suggestion.

Mentors for EvalAI-ngx Project (@aka-jain @spyshiv @shivaniprakash95 @RishabhJain2018 @deshraj) will try to respond to this thread ASAP so that you are not blocked.

**Comment by gautamjajoo** [comment]
@spyshiv @RishabhJain2018 @deshraj Can I work on this? Or is this only for GSOC students.

**Comment by spyshiv** [comment]
@gautamjajoo You can work on any issue there is no restriction. Go ahead with this issue.
