### ISSUE TITLE
TravisCI Build fails while waiting for an input to surge.sh

### ISSUE THREAD

**Issue by live-wire** [Cloud-CV/EvalAI-ngx#57]
## I'm submitting a
- [x] CI enhancement

## Current behavior
Travis CI builds fail after 10mins as Surge expects an email input which it doesn't get.

## Steps to reproduce
Create any Pull Request (or a new commit in any of the existing Pull Requests)

Useful link:
https://surge.sh/help/integrating-with-travis-ci

**Comment by deshraj** [comment]
@live-wire Can you please look into this issue? I won't get time until next week to look into this.

**Comment by live-wire** [comment]
Yeah I'm on it 🍺 
I'll reach out to you If i have doubts.

**Comment by deshraj** [comment]
Sounds good. Thanks a lot for taking lead on this.

**Comment by RishabhJain2018** [comment]
@live-wire Please feel free to close the issue if this is completed.

**Comment by live-wire** [comment]
This was resolved as part of #58
