### ISSUE TITLE
 UI Design for Contact Us page

### ISSUE THREAD

**Issue by shivaniprakash19** [Cloud-CV/EvalAI-ngx#59]
**Here is the final design. Please refer to screenshot below.**

![contact_us_final](https://user-images.githubusercontent.com/12206049/39630054-d1848c0e-4fcb-11e8-9a11-f5b400f13f80.jpg)

**You can refer to the following image for further details on creating the page :**

![contact_us_final_documentation](https://user-images.githubusercontent.com/12206049/39630093-e8d2bab6-4fcb-11e8-94df-996cb67e5ef5.jpg)

You can refer to the following image for further details on creating the page :
https://drive.google.com/drive/folders/12WqC1rHA2rakJQLr-FTjZnn4lj0uPXTv

You can get the relevant text from the present website itself: https://evalai.cloudcv.org/contact

Please comment below if you want to work on this or in case of any question/suggestion.

Mentors for EvalAI-ngx Project (@aka-jain @spyshiv @shivaniprakash95 @RishabhJain2018 @deshraj) will try to respond to this thread ASAP so that you are not blocked.

**Comment by live-wire** [comment]
@shivaniprakash95 @deshraj  Should the map in the background be an image (redirects to maps.google.com when clicked) or an interactive Map View ?

**Comment by shivaniprakash19** [comment]
@live-wire I think the interactive one would be more realistic and better. @aka-jain @deshraj What are your views on it?

**Comment by RishabhJain2018** [comment]
Closing this since it is already merged.
