### ISSUE TITLE
Setup Docs for EvalAI-ngx using Github Pages

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI-ngx#6]

**Comment by muddlebee** [comment]
hey @deshraj  can I take this up? also by github pages do you mean wiki ?

**Comment by deshraj** [comment]
@anweshknayak: Sure. You can put documentation files in the docs/ directory which we can host using Github Pages.

**Comment by aka-jain** [comment]
@anweshknayak are you working on this?

**Comment by muddlebee** [comment]
@aka-jain Can you help me a bit here? Do I include every doc as it is in here https://github.com/Cloud-CV/EvalAI/tree/master/docs.

**Comment by aka-jain** [comment]
@deshraj please have a look here.

**Comment by deshraj** [comment]
Sorry @anweshknayak for the confusion. For now, you can just add the docs related to setting up the project (what is there in README of EvalAI-ngx) and then we can as we make progress, we can add more docs.

**Comment by S2606** [comment]
Is anyone working on this??

**Comment by muddlebee** [comment]
@S2606 I am. Will send a PR soon :smile:
