### ISSUE TITLE
UI Design for All Challenges page

### ISSUE THREAD

**Issue by shivaniprakash19** [Cloud-CV/EvalAI-ngx#60]
**Here is the final design. Please refer to the screenshots below.**

(There are two screenshots here, of the same page : 
-The first one shows how the page should look if the filter tabs Ongoing and Upcoming challenges are selected, and the Side upper tag showing which one is what(either upcoming or ongoing.
-The second screenshot shows a scenario if all the filter tabs are selected then the side upper tag in each box changes, you can notice the one in the last box changes to the brown color)

![evalai_redesign_all_challenges_final_1](https://user-images.githubusercontent.com/12206049/39649318-10ffc204-5003-11e8-9a68-a95862ea239e.jpg)
![evalai_redesign_all_challenges_final_2](https://user-images.githubusercontent.com/12206049/39649325-156daf2c-5003-11e8-941c-d8c5c2911e71.jpg)

**You can refer to the following image for further details on creating the page : **

![all-challenge_final_documentation](https://user-images.githubusercontent.com/12206049/39649543-c36e7318-5003-11e8-9cad-21f65c8da6f7.jpg)

You can get all the related assets for creating the page from the link below : 
https://drive.google.com/drive/folders/1fhWkj6Ir7HLZzwBZoPCKyyoS-ulFdmg_

The screenshot shows the dummy text, it's just for illustration purpose. You can refer to the current page of the website to find the exact data: https://evalai.cloudcv.org/web/challenges/list

Please comment below if you want to work on this or in case of any question/suggestion.

Mentors for EvalAI-ngx Project (@aka-jain @spyshiv @shivaniprakash95 @RishabhJain2018 @deshraj) will try to respond to this thread ASAP so that you are not blocked.

**Comment by RishabhJain2018** [comment]
Closing this since it is already merged.
