### ISSUE TITLE
Docker setup is not working

### ISSUE THREAD

**Issue by spyshiv** [Cloud-CV/EvalAI-ngx#75]
## I'm submitting a

(Check one with "x" from given options)
- [x] Bug report

It's happening After [this](https://github.com/Cloud-CV/EvalAI/commit/e9840b57f549a5522ff9fce3be94f0b064182093) commit in [evalai](https://github.com/Cloud-CV/EvalAI/) repo. 
@RishabhJain2018 @deshraj

**Comment by RishabhJain2018** [comment]
okay @spyshiv . I'll look into it 👍

**Comment by RishabhJain2018** [comment]
Closing this for now. We'll revisit it later if needed.
