### ISSUE TITLE
Custom Toasts

### ISSUE THREAD

**Issue by live-wire** [Cloud-CV/EvalAI-ngx#76]
## I'm submitting a

- [ ] Bug report
- [x] Feature request

## Expected behavior
Need custom toasts/messages for success or failure of API requests.

Please post the designs here @shivaniprakash95 🍡 

cc: @deshraj @RishabhJain2018 @spyshiv @aka-jain

**Comment by shivaniprakash19** [comment]
This is the link to both SVG and PNG files:
https://drive.google.com/drive/folders/1w2QRyWaB6flCLF1meuZqPwCqxz5cqBgK
Please let me know if you need any further help regarding this.

**Comment by RishabhJain2018** [comment]
Closing this since it is already merged.
