### ISSUE TITLE
Use compressed images and assets

### ISSUE THREAD

**Issue by live-wire** [Cloud-CV/EvalAI-ngx#79]
## I'm submitting a 

- [ ] Bug report
- [x] Feature request

The png resources are heavy as of now. Replace all by compressed png files before taking ngx to production 💻 

> Creating this issue now so we don't lose track of it.

**Comment by wadleo** [comment]
Hi @live-wire can someone work on this as a GSOC warmup? Also, I can see some assets are more than 1MB, I am thinking of manually replacing each of those with a compressed version, any recommendations of tools to use with my approach?

**Comment by RishabhJain2018** [comment]
Hi @wadleo, you can work on it as a GSoC warmup issue. Moreover, as of now, we don't have any strong preferences for tools being used for compressing the image.

**Comment by wadleo** [comment]
@RishabhJain2018 are there any other resources that need to be compressed, as I noticed only one was left in the assets folder

**Comment by RishabhJain2018** [comment]
No, for now you can compress that resource and start working up on other issues.

**Comment by wadleo** [comment]
@RishabhJain2018 did that already here #95

**Comment by harshsahu97** [comment]
has this issue already been resolved?
