### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI-ngx#81]
The current readme should be updated by including badges. Following list should be added:

1. Codecov
2. Travis-CI

Also modify the last line of readme with
`EvalAI-ngx is currently maintained by [Akash Jain](http://www.jainakash.in/), [Shiv Baran Singh](http://www.shivbaran.in/), [Shivani Prakash Gupta](https://www.behance.net/shivaniprakash19), [Rishabh Jain](https://rishabhjain2018.github.io/) and [Deshraj Yadav](https://deshraj.github.io)`

**Comment by zurda** [comment]
I'd like to take this one, if it's up for grabs

**Comment by RishabhJain2018** [comment]
@hakabuk Yes it's available! Go ahead.
