### ISSUE TITLE
404 Page

### ISSUE THREAD

**Issue by live-wire** [Cloud-CV/EvalAI-ngx#86]
## I'm submitting a

(Check one with "x" from given options)
- [ ] Bug report
- [x] Feature request

Need a 404 page for paths that are not found by app-router.

**Comment by pavanrkadave** [comment]
Can i work on this issue?

**Comment by RishabhJain2018** [comment]
@pavanrkadave Sure! go ahead. Please feel free to ask if you have doubts/questions.

**Comment by live-wire** [comment]
There is a 404 page built as a part of the pull-request #90 
It can be found here: https://pr-90-evalai.surge.sh/ (Click on `News` in the header to access the 404 page.)
@pavanrkadave You could take a pull of that PR and see how to organize your new components/ 404-component 😄 
cc: @RishabhJain2018

**Comment by RishabhJain2018** [comment]
Thanks @live-wire for the heads-up.

**Comment by pavanrkadave** [comment]
Hi @live-wire, So i need to make the similar changes to this issue as well right?

**Comment by live-wire** [comment]
That would be a good starting point. We can iterate if we need any design changes after that @pavanrkadave

**Comment by pavanrkadave** [comment]
Ok, but the version I have cloned does not have the latest code structure.

**Comment by pavanrkadave** [comment]
I have made the changes, can i get the further instructions to create a PR
@live-wire @RishabhJain2018 ?

**Comment by live-wire** [comment]
@pavanrkadave Follow the [contribution guidelines](https://github.com/Cloud-CV/EvalAI/blob/master/.github/CONTRIBUTING.md) on EvalAI. Have a look at the other open/merged PRs for tips.

**Comment by pavanrkadave** [comment]
Can you assign me this issue? @live-wire

**Comment by Abhi58** [comment]
Hi @live-wire @RishabhJain2018 . I don't see the code update for 404 page as in PR #90 . Why is  the code not merged yet? Let me know if i can continue working with this issue.

**Comment by RishabhJain2018** [comment]
Hi @Abhi58, We have the code for 404 page in the master branch now. @live-wire had already added it. Hence, closing this issue.
Please take up the issues labeled as `GSoC-2019`.
