### ISSUE TITLE
Need a Loader animation for all API calls.

### ISSUE THREAD

**Issue by live-wire** [Cloud-CV/EvalAI-ngx#87]
## I'm submitting a

(Check one with "x" from given options)
- [ ] Bug report
- [x] Feature request

Need a loader animation for all API calls.

**Comment by Shekharrajak** [comment]
Hi,

Please let me know what will be running in `http://localhost:8000/api/` .

**Comment by RishabhJain2018** [comment]
Hi @Shekharrajak, 
To answer your question, the Django server will be running on `http://localhost:8000/api/`.

Closing this issue since we have this.
