### ISSUE TITLE
Create a separate file for all API paths

### ISSUE THREAD

**Issue by live-wire** [Cloud-CV/EvalAI-ngx#89]
## I'm submitting a

(Check one with "x" from given options)
- [ ] Bug report
- [x] Feature request

Separate file for all the API paths.

**Comment by Shekharrajak** [comment]
Hi, 

Can you please exaplin more about it and an example stating what need to be done ?

**Comment by RishabhJain2018** [comment]
Hi @Shekharrajak , @live-wire have already added this file.
Please feel free to take up any of the deliverables from here: https://github.com/Cloud-CV/GSoC-Ideas/issues/23
