### ISSUE TITLE
Fix failing travis build

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI-ngx#94]
The `master` branch Travis build is failing due to this reason: https://travis-ci.org/Cloud-CV/EvalAI-ngx/jobs/501229397#L549

**Comment by Abhi58** [comment]
Hi @RishabhJain2018 . We are not supposed to use forRoot() for NgxTwitterTimelineModule.  Also after removing forRoot()  i am facing "export 'defineInjectable' was not found in '@angular/core' issue which seems to break the website. Apparantely, this issue exists in all angular versions below 6. I am working on this issue right now. I would be glad if i could get any help regarding the issue.
Also, I want to ask if are we planning to upgrade to angular 6?

**Comment by Abhi58** [comment]
Please assign this issue to me

**Comment by KhalidRmb** [comment]
I would like to take this on! :) @RishabhJain2018

**Comment by Abhi58** [comment]
@RishabhJain2018 In PR #96 `ng build` command is running properly but [surge](https://travis-ci.org/Cloud-CV/EvalAI-ngx/builds/502683664#L655) is not able to login. Please look into this issue.

**Comment by Shekharrajak** [comment]
I think, the travis environment variable for this repository (`SURGE_LOGIN`, `SURGE_TOKEN` )  is causing the problem [as per this article](https://surge.sh/help/integrating-with-travis-ci).

**Comment by lunayach** [comment]
Yes, the Travis-build passes till the PR-deploy step. I guess, you'll need to be added as a collaborator in  surge and then it will deploy the PR on [pr-94-evalai.surge.sh](pr-94-evalai.surge.sh), passing the build.
