### ISSUE TITLE
Numerous build errors prevents the project from compiling

### ISSUE THREAD

**Issue by wadleo** [Cloud-CV/EvalAI-ngx#97]
- [x ] Bug report
- [ ] Feature request

## Current behavior
Numerous build errors prevent the project from compiling. Some include;
- @angular/compiler-cli@5.2.11 requires typescript@'>=2.4.2 <2.7.0' but 2.9.2 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.
- ERROR in src/app/app.module.ts(116,30): error TS2339: Property 'forRoot' does not exist on type 'typeof NgxTwitterTimelineModule'.

## Expected behavior
After running ng serve project should compile with without errors

## Steps to reproduce
Run ng serve

## Related screenshots

![screenshot-20190306184807-1190x502](https://user-images.githubusercontent.com/11006276/53901972-7e25c580-4040-11e9-97f7-d60b44f3fc22.png)

## System information
OS: Kali linux
Npm: 6.7.0
Node: v11.8.0

**Comment by wadleo** [comment]
@RishabhJain2018 @live-wire please can you guide me to solve this, thanks. Recommendations from npm include updating typescript 
npm install typescript@'>=2.4.2 <2.7.0'

**Comment by Abhi58** [comment]
'ERROR in src/app/app.module.ts(116,30): error TS2339: Property 'forRoot' does not exist on type 'typeof NgxTwitterTimelineModule'. This error has just been fixed. Please refer to PR #96.

**Comment by wadleo** [comment]
Okay @abhi58, I will test and close this, thanks. For the fix

**Comment by wadleo** [comment]
@Abhi58 yes #96  fixes this, so I'm closing this, thanks again for your help.
